[project]
name = "myoci-toolkit"
version = "1.0.0"
description = "A personal, intelligent wrapper for the OCI CLI."
authors = [{ name = "Archie", email = "archie@example.com" }]
requires-python = ">=3.8"
dependencies = [
    "typer[all]",
    "python-dotenv",
    "rich",
]

[project.scripts]
myoci = "myoci:app"
